PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS avatars(id TEXT PRIMARY KEY, vrchat_id TEXT UNIQUE, name TEXT NOT NULL, custom_version TEXT NOT NULL DEFAULT '0.0.0', archived INTEGER NOT NULL DEFAULT 0, favorite INTEGER NOT NULL DEFAULT 0, notes TEXT NOT NULL DEFAULT '', local_cover_path TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, last_api_refresh_at TEXT, data_json TEXT NOT NULL CHECK(json_valid(data_json)));
CREATE TABLE IF NOT EXISTS avatar_packages(id TEXT PRIMARY KEY, avatar_id TEXT NOT NULL REFERENCES avatars(id) ON DELETE CASCADE, platform TEXT NOT NULL, data_json TEXT NOT NULL CHECK(json_valid(data_json)));
CREATE TABLE IF NOT EXISTS avatar_snapshots(id TEXT PRIMARY KEY, avatar_id TEXT NOT NULL REFERENCES avatars(id) ON DELETE CASCADE, vrchat_version INTEGER NOT NULL, snapshot_json TEXT NOT NULL CHECK(json_valid(snapshot_json)), created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS releases(id TEXT PRIMARY KEY, avatar_id TEXT NOT NULL REFERENCES avatars(id) ON DELETE CASCADE, version TEXT NOT NULL, title TEXT NOT NULL, description TEXT NOT NULL, released_at TEXT NOT NULL, created_at TEXT NOT NULL, UNIQUE(avatar_id,version), UNIQUE(id,avatar_id));
CREATE TABLE IF NOT EXISTS changelog_entries(id TEXT PRIMARY KEY, avatar_id TEXT NOT NULL REFERENCES avatars(id) ON DELETE CASCADE, release_id TEXT, title TEXT NOT NULL, description TEXT NOT NULL, importance TEXT NOT NULL, platform TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, FOREIGN KEY(release_id,avatar_id) REFERENCES releases(id,avatar_id));
CREATE TABLE IF NOT EXISTS changelog_categories(id TEXT PRIMARY KEY, name TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS changelog_entry_categories(entry_id TEXT NOT NULL REFERENCES changelog_entries(id) ON DELETE CASCADE, category_id TEXT NOT NULL REFERENCES changelog_categories(id), PRIMARY KEY(entry_id,category_id));
CREATE TABLE IF NOT EXISTS tags(id TEXT PRIMARY KEY, name TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS avatar_tags(avatar_id TEXT NOT NULL REFERENCES avatars(id) ON DELETE CASCADE, tag_id TEXT NOT NULL REFERENCES tags(id) ON DELETE CASCADE, PRIMARY KEY(avatar_id,tag_id));
CREATE TABLE IF NOT EXISTS todos(id TEXT PRIMARY KEY, avatar_id TEXT NOT NULL REFERENCES avatars(id) ON DELETE CASCADE, title TEXT NOT NULL, priority TEXT NOT NULL, completed INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS attachments(id TEXT PRIMARY KEY, avatar_id TEXT NOT NULL REFERENCES avatars(id) ON DELETE CASCADE, changelog_entry_id TEXT REFERENCES changelog_entries(id) ON DELETE SET NULL, path TEXT NOT NULL, type TEXT NOT NULL, caption TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS osc_snapshots(id TEXT PRIMARY KEY, avatar_id TEXT NOT NULL REFERENCES avatars(id) ON DELETE CASCADE, data_json TEXT NOT NULL CHECK(json_valid(data_json)), created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS activity_log(id TEXT PRIMARY KEY, avatar_id TEXT REFERENCES avatars(id) ON DELETE SET NULL, type TEXT NOT NULL, message TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_avatars_updated ON avatars(updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_packages_avatar ON avatar_packages(avatar_id);
CREATE INDEX IF NOT EXISTS idx_snapshots_avatar_date ON avatar_snapshots(avatar_id,created_at DESC);
CREATE INDEX IF NOT EXISTS idx_changes_avatar_date ON changelog_entries(avatar_id,created_at DESC);
CREATE INDEX IF NOT EXISTS idx_changes_release ON changelog_entries(release_id);
CREATE INDEX IF NOT EXISTS idx_releases_avatar_date ON releases(avatar_id,released_at DESC);
CREATE INDEX IF NOT EXISTS idx_todos_avatar ON todos(avatar_id);
CREATE INDEX IF NOT EXISTS idx_attachments_avatar ON attachments(avatar_id);
CREATE INDEX IF NOT EXISTS idx_osc_avatar ON osc_snapshots(avatar_id,created_at DESC);
CREATE INDEX IF NOT EXISTS idx_activity_date ON activity_log(created_at DESC);
PRAGMA user_version=1;
