using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json.Linq;
using UnityEngine;
using UnityEngine.Profiling;
using UnityEditor;
namespace VRCAvatarVault {
 internal static class AvatarExtractor {
  internal static Component[] Avatars(){return UnityEngine.Object.FindObjectsOfType<Transform>(true).SelectMany(t=>t.GetComponents<Component>()).Where(c=>c&&c.GetType().Name=="VRCAvatarDescriptor"&&c.gameObject.scene.IsValid()).ToArray();}
  internal static string PathOf(Transform t,Transform root){if(t==root)return root.name;var parts=new List<string>();while(t&&t!=root){parts.Insert(0,t.name);t=t.parent;}return root.name+"/"+string.Join("/",parts);}
  internal static JObject Capture(Component descriptor,string platform){if(!descriptor)throw new Exception("Select an avatar descriptor");var root=descriptor.gameObject;var hierarchy=new JArray();var transforms=root.GetComponentsInChildren<Transform>(true);if(transforms.Length>20000)throw new Exception("Avatar exceeds 20,000 objects");foreach(var t in transforms){var components=new JArray();foreach(var c in t.GetComponents<Component>()){if(!c){components.Add(new JObject{["type"]="Missing script"});continue;}components.Add(new JObject{["id"]=SerializedReader.Id(c),["type"]=c.GetType().FullName,["properties"]=SerializedReader.Properties(c)});}hierarchy.Add(new JObject{["id"]=SerializedReader.Id(t.gameObject),["parentId"]=t==root.transform?null:SerializedReader.Id(t.parent.gameObject),["path"]=PathOf(t,root.transform),["name"]=t.name,["active"]=t.gameObject.activeSelf,["components"]=components});}
   var renderers=root.GetComponentsInChildren<Renderer>(true);var materials=renderers.SelectMany(x=>x.sharedMaterials).Where(m=>m).Distinct().ToArray();var textures=new HashSet<Texture>();var materialData=new JArray();foreach(var m in materials){materialData.Add(new JObject{["id"]=SerializedReader.Id(m),["name"]=m.name,["path"]=AssetDatabase.GetAssetPath(m),["shader"]=m.shader?m.shader.name:null});foreach(var prop in m.GetTexturePropertyNames()){var t=m.GetTexture(prop);if(t)textures.Add(t);}}
   var textureData=new JArray(textures.Select(t=>new JObject{["id"]=SerializedReader.Id(t),["name"]=t.name,["width"]=t.width,["height"]=t.height,["memoryBytes"]=Profiler.GetRuntimeMemorySizeLong(t)}));
   var meshes=root.GetComponentsInChildren<MeshFilter>(true).Select(x=>x.sharedMesh).Concat(root.GetComponentsInChildren<SkinnedMeshRenderer>(true).Select(x=>x.sharedMesh)).Where(m=>m).ToArray();long triangles=0;foreach(var m in meshes)for(int i=0;i<m.subMeshCount;i++)if(m.GetTopology(i)==MeshTopology.Triangles)triangles+=(long)m.GetIndexCount(i)/3;
   var all=root.GetComponentsInChildren<Component>(true).Where(c=>c).ToArray();
   var metrics=new JObject{["triangles"]=triangles,["vertices"]=meshes.Sum(m=>(long)m.vertexCount),["meshes"]=meshes.Length,["skinnedMeshes"]=root.GetComponentsInChildren<SkinnedMeshRenderer>(true).Length,["materials"]=renderers.Sum(x=>x.sharedMaterials.Count(m=>m)),["uniqueMaterials"]=materials.Length,["bones"]=root.GetComponentsInChildren<SkinnedMeshRenderer>(true).SelectMany(s=>s.bones).Where(t=>t).Distinct().Count(),["animators"]=root.GetComponentsInChildren<Animator>(true).Length,["physBones"]=all.Count(c=>c.GetType().Name=="VRCPhysBone"),["contacts"]=all.Count(c=>c.GetType().Name=="VRCContactReceiver"||c.GetType().Name=="VRCContactSender"),["constraints"]=all.Count(c=>c.GetType().Name.EndsWith("Constraint")),["particleSystems"]=root.GetComponentsInChildren<ParticleSystem>(true).Length,["particles"]=root.GetComponentsInChildren<ParticleSystem>(true).Sum(p=>(long)p.main.maxParticles),["lights"]=root.GetComponentsInChildren<Light>(true).Length,["audioSources"]=root.GetComponentsInChildren<AudioSource>(true).Length,["cloth"]=root.GetComponentsInChildren<Cloth>(true).Length,["textureMemoryBytes"]=textures.Sum(t=>Profiler.GetRuntimeMemorySizeLong(t))};
   string blueprint=null;var pipeline=all.FirstOrDefault(c=>c.GetType().Name=="PipelineManager");if(pipeline)using(var so=new SerializedObject(pipeline)){blueprint=so.FindProperty("blueprintId")?.stringValue;}
   return new JObject{["schemaVersion"]=1,["source"]="unity_editor_plugin",["capturedAt"]=DateTime.UtcNow.ToString("o"),["platform"]=platform,["unityVersion"]=Application.unityVersion,["avatarName"]=root.name,["blueprintId"]=blueprint,["hierarchy"]=hierarchy,["parameters"]=ExpressionExtractor.Parameters(descriptor),["menus"]=ExpressionExtractor.Menus(descriptor),["controllers"]=AnimatorExtractor.Read(root,descriptor),["descriptor"]=SerializedReader.Properties(descriptor),["materials"]=materialData,["textures"]=textureData,["metrics"]=metrics,["performanceRating"]=null,["metricBasis"]="Authored scene; editor texture memory estimate; before build optimizers",["limitations"]=new JArray("Component properties limited to depth 3 and 512 entries per component.","Large serialized arrays are not expanded.","Unsaved objects use session-local IDs; save the scene for stable comparisons.","Controller override maps and build-time optimizer output require inspection in Unity.")};
  }
 }
}
