using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using UnityEditor;
using Object=UnityEngine.Object;
namespace VRCAvatarVault {
 internal static class ExpressionExtractor {
  internal static JToken Parameters(Object descriptor){var asset=SerializedReader.ObjectField(descriptor,"expressionParameters");if(!asset)return JValue.CreateNull();var list=new JArray();using(var so=new SerializedObject(asset)){var parameters=so.FindProperty("parameters");if(parameters==null||!parameters.isArray)return JValue.CreateNull();for(int i=0;i<parameters.arraySize;i++){var p=parameters.GetArrayElementAtIndex(i);list.Add(new JObject{["name"]=SerializedReader.Value(p.FindPropertyRelative("name")),["type"]=SerializedReader.Value(p.FindPropertyRelative("valueType")),["defaultValue"]=SerializedReader.Value(p.FindPropertyRelative("defaultValue")),["saved"]=SerializedReader.Value(p.FindPropertyRelative("saved")),["synced"]=SerializedReader.Value(p.FindPropertyRelative("networkSynced"))});}}return list;}
  internal static JToken Menus(Object descriptor){var root=SerializedReader.ObjectField(descriptor,"expressionsMenu");if(!root)return JValue.CreateNull();var output=new JArray();var visited=new HashSet<int>();Visit(root,visited,output);return output;}
  private static void Visit(Object asset,HashSet<int> visited,JArray output){if(!asset||!visited.Add(asset.GetInstanceID())||visited.Count>512)return;var controls=new JArray();var children=new List<Object>();using(var so=new SerializedObject(asset)){var array=so.FindProperty("controls");if(array!=null&&array.isArray)for(int i=0;i<array.arraySize&&i<256;i++){var c=array.GetArrayElementAtIndex(i);var submenu=c.FindPropertyRelative("subMenu")?.objectReferenceValue;var sub=new JArray();var sp=c.FindPropertyRelative("subParameters");if(sp!=null&&sp.isArray)for(int j=0;j<sp.arraySize;j++)sub.Add(SerializedReader.Value(sp.GetArrayElementAtIndex(j).FindPropertyRelative("name")));controls.Add(new JObject{["name"]=SerializedReader.Value(c.FindPropertyRelative("name")),["type"]=SerializedReader.Value(c.FindPropertyRelative("type")),["parameter"]=SerializedReader.Value(c.FindPropertyRelative("parameter")?.FindPropertyRelative("name")),["value"]=SerializedReader.Value(c.FindPropertyRelative("value")),["subParameters"]=sub,["submenuId"]=SerializedReader.Id(submenu),["icon"]=SerializedReader.Value(c.FindPropertyRelative("icon"))});if(submenu)children.Add(submenu);}}output.Add(new JObject{["id"]=SerializedReader.Id(asset),["name"]=asset.name,["controls"]=controls});foreach(var child in children)Visit(child,visited,output);}
 }
}
